# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "dark" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Tri Wanda Septian's Blog"
title_separator          : "|"
subtitle                 : "#neverstoplearning #lifelonglearning"
name                     : "Tri Wanda Septian's Blog and Stuff"
description              : "just a simple blog from perpetual learner"
url                      : "https://twseptian.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/"
repository               : "twseptian/twseptian.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/teaser.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/ava.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : "Tri Wanda Septian" # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "utterances", "custom"
  disqus:
    shortname            : "https-twseptian-github-io" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : 2 # 5 (default)
    colorscheme          : "dark" # "light" (default), "dark"
  utterances:
    theme                : "github-dark" # "github-dark" # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : "lunr"
algolia:
  application_id         : "QB6HVGBSBA"
  index_name             : "dev_minimal-mistakes"
  search_only_api_key    : "9d5014e5bbc77372547bce778dfa5663"
  powered_by             : true

# SEO Related
google_site_verification : "KJV9Ip5Mlud9lmDhN6pzfrcplPaoPSnsaOptFO6aIwE"
bing_site_verification   : "A990426F952EA8940B6F2C13C11817E3"
yandex_site_verification :

# google search engine ID
google:
  search_engine_id: "e3a64b70d8f3bdde7"

# Social Sharing
twitter:
  username               : "twseptian_"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/assets/images/avatar_backup.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - https://twitter.com/twsepian_
    - https://github.com/twseptian

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :

# Site Author
author:
  name             : "Tri Wanda Septian"
  avatar           : "/assets/images/avatar_backup.png"
  bio              : "Researcher, Infosec practioner,<br>CTF Player, Perpetual Learner."
  location         : "Indonesia"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://twseptian.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:twseptian@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/twseptian"
    - label: "GitLab"
      icon: "fab fa-gitlab"
      url: "https://gitlab.com/twseptian/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/twseptian_"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/twseptian/"

# Site Footer
footer:
  links:
    #- label: "HackTheBox"
    #  icon: "fas fa-fw fa-cube"
    #  url: "https://app.hackthebox.eu/profile/183432"
    #- label: "TryHackMe"
    #  icon: "fas fa-fw fa-cloud"
    #  url: "https://tryhackme.com/p/twsterlab"            
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"
    - label: "Buy Me a Coffee"
      icon: "fas fa-mug-hot"
      url: "https://www.buymeacoffee.com/twseptian"
    #- label: "Credly"
    #  icon: "fas fa-user-circle"
    #  url: "https://www.credly.com/users/tri-wanda-septian/badges"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 2 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
  pets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
  # _pets
  - scope:
      path: ""
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
